name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-22.04  # Use Ubuntu 22.04 server image
    steps:
      - uses: actions/checkout@v3

      # Open necessary ports (for HTTP, HTTPS, and Vesta Control Panel)
      - name: Open necessary ports
        run: |
          sudo ufw allow 80/tcp   # Allow HTTP
          sudo ufw allow 443/tcp  # Allow HTTPS
          sudo ufw allow 22/tcp   # Allow SSH
          sudo ufw allow 8083/tcp # Vesta CP Admin Panel
          sudo ufw --force enable # Enable the firewall with rules

      # Install Vesta Control Panel
      - name: Install Vesta Control Panel
        run: |
          # Download the latest VestaCP install script directly
          curl -sL https://github.com/serghey-rodin/vst-install-v2/blob/master/vst-install.sh -o vst-install.sh
          sudo bash vst-install.sh

      # Install PHP and required dependencies for the API server
      - name: Install PHP and required extensions
        run: |
          sudo apt update
          sudo apt install -y php php-cli php-fpm php-mysql

      # Start PHP-based API server using PHP's built-in server
      - name: Start PHP API server
        run: |
          nohup php -S 0.0.0.0:8000 -t ./public &

      # Run SSHX and open a remote terminal session
      - name: Open SSHX remote terminal session
        run: |
          curl -sSf https://sshx.io/get | sh -s run
